# pytest.ini is a configuration file fused by pytest to control how your tests run - without having to type long command-line options again and again
# Run tests simply with : pytest

[pytest]
#for html report generation
addopts = --headed 
          --browser chromium
        ;   --video=retain-on-failure
        ;   --screenshot=only-on-failure
        ;   --tracing=retain-on-failure
        ;   --html=reports/report.html --self-contained-html --capture=tee-sys
          --alluredir=reports/EsapePlan_Allure_Report

testpaths = tests --slowmo=200