# pytest.ini is a configuration file fused by pytest to control how your tests run - without having to type long command-line options again and again
# Run tests simply with : pytest

[pytest]
addopts = --headed --browser chromium --html=reports/report.html --self-contained-html
testpaths = tests --slowmo=200